### PR TITLE
code tidy, added tfs for convex_hull + BoundingBox

### LINKED ISSUE #36: lidar_euclidean_cluster_detect output topics are not transformed properly.
/label ~bug

### Required information:
- Operating system and version: Ubuntu 18.04
- Autoware installation type: Source
- Autoware version or commit hash OAP7
- ROS distribution and version: Ros melodic
- ROS installation type: APT
- Package or library, if applicable: lidar_euclidean_cluster_detect

### Description of the bug

lidar_euclidean_cluster_detect output topics are not fully transformed.

#### CloudCluster in `/detection/lidar_detector/cloud_clusters`

Transformed properly :
 - `min_point`
 - `max_point`
 - `avg_point`
 - `centroid_point`

Not transformed : 
 - `convex_hull`
 - `bounding_box`

Because this message is not TFed properly the messages published in `/detection/lidar_detector/objects` are also wrong :

#### DetectedObject in `/detection/lidar_detector/objects`

Transformed properly :
 - None

Not transformed : 
 - `pose`
 - `convex_hull`

### Steps to reproduce the bug

 - Configure lidar_euclidean_cluster_detect output frame different from the input frame.
 - Publish pointclouds to the `/points_raw` topic.
 - Open rqt and notice that some data is not tfed.

### Screenshots

image
The points are still in Lidar frame and not map frame, even if the header says so ! It really looks like a bug.

### Additional information

I have corrected the bug.
One question though, what is the best way to TF a [Point32](http://docs.ros.org/en/melodic/api/geometry_msgs/html/msg/Point32.html) ? Because the TF listener has no `transformPoint32` function.

Thanks !

### PR DESCRIPTION
**Pull request by MaxandreOgeret**
### Fixed bug

lidar_euclidean_cluster_detect output topics are not fully transformed.
Fix #36 
### Fix applied

I transformed convex_hull and BoundingBox to the expected output_frame given in parameter.
For this I had to generate PointStamped and then transform them. (Is it the best way ?)

I also tidied the surrounding of the code I changed, using clearer names, and switching to range-based loop.
Upon request I'm willing to tidy the code a bit more.
I hope this work is useful ! :)

### CODE REVIEW

File: lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp [hunk 1]
```diff
@@ -224,33 +224,58 @@ void publishCloudClusters(const ros::Publisher *in_publisher, const autoware_msg
...
-        _transform_listener->transformPoint(in_target_frame, ros::Time(), i->centroid_point, in_header.frame_id,
+        _transform_listener->transformPoint(in_target_frame, ros::Time(), cluster.centroid_point, in_header.frame_id,
                                             cluster_transformed.centroid_point);
 
-        cluster_transformed.dimensions = i->dimensions;
-        cluster_transformed.eigen_values = i->eigen_values;
-        cluster_transformed.eigen_vectors = i->eigen_vectors;
+        // Convex_hull
+        geometry_msgs::PolygonStamped polygon_tfed;
+        for (geometry_msgs::Point32 point : cluster.convex_hull.polygon.points) {
```
Comment (JWhitleyWork) [inline lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp:247]: This could also be `const auto & point` to avoid a copy for each point.

File: lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp [hunk 2]
```diff
@@ -224,33 +224,58 @@ void publishCloudClusters(const ros::Publisher *in_publisher, const autoware_msg
...
+            geometry_msgs::Point32 new_point32;
+            new_point_stamped.header = in_header;
+            new_point_stamped.point.x = point.x;
+            new_point_stamped.point.y = point.y;
+            new_point_stamped.point.z = point.z;
+            _transform_listener->transformPoint(in_target_frame, ros::Time(), new_point_stamped, in_header.frame_id, new_point_stamped_tfed);
+            new_point32.x = new_point_stamped_tfed.point.x;
+            new_point32.y = new_point_stamped_tfed.point.y;
+            new_point32.z = new_point_stamped_tfed.point.z;
+            polygon_tfed.polygon.points.push_back(new_point32);
```
Comment (JWhitleyWork) [inline lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp:259]: This would be significantly faster and avoid a couple of copies if you pre-allocated `polygon_tfed.polygon.points` with

```
polygon_tfed.polygon.points.resize(cluster.convex_hull.polygon.points.size())
```

And then referenced the properties of each `point` by ID or an iterator.

Additionally, allocating `new-point_stamped` and `new_point_stamped_tfed` outside this loop and re-using them would save ref/de-ref time.

**Review by JWhitleyWork — COMMENTED** [review]
Just some optimization suggestions. If you'd like to implement them, I'm happy to accept the changes - if not, let me know and I'll approve as-is.

**Comment by MaxandreOgeret** [comment]
> Just some optimization suggestions. If you'd like to implement them, I'm happy to accept the changes - if not, let me know and I'll approve as-is.

I will make the changes over the weekend.

File: lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp (hunk 1 above)
Comment (MaxandreOgeret) [reply lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp]: I used a classical for loop to solve your next request more easily.

File: lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp (hunk 2 above)
Comment (MaxandreOgeret) [reply lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp]: Thanks for that ! I finally decided to directly resize `cluster_transformed.convex_hull.polygon.points` with
```c++
cluster_transformed.convex_hull.polygon.points.resize(cluster.convex_hull.polygon.points.size());
```

It removes the need for an intermediate polygon.

`new_point_stamped` & `new_point_stamped_tfed` are now allocated outside the for loop.

Comment (MaxandreOgeret) [reply lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp]: What do you think ?

Comment (JWhitleyWork) [reply lidar_euclidean_cluster_detect/nodes/lidar_euclidean_cluster_detect/lidar_euclidean_cluster_detect.cpp]: LGTM.

**Review by JWhitleyWork — APPROVED** [review]
Thanks for working on this!
